# Generated by Django 6.0 on 2026-04-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='nombre')),
                ('company', models.CharField(blank=True, max_length=140, verbose_name='empresa o proyecto')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('service', models.CharField(choices=[('climatizacion', 'Climatización'), ('aire-acondicionado', 'Aire acondicionado'), ('ventilacion', 'Ventilación'), ('extraccion', 'Extracción'), ('presurizacion', 'Presurización'), ('mantenciones', 'Mantenciones'), ('otro', 'Otro requerimiento')], max_length=40, verbose_name='servicio requerido')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('message', models.TextField(verbose_name='detalle del requerimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso')),
            ],
            options={
                'verbose_name': 'solicitud de contacto',
                'verbose_name_plural': 'solicitudes de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
