PROJECT_CATEGORIES = [
    {"id": "all", "label": "Todos"},
    {"id": "climatizacion", "label": "Climatización"},
    {"id": "ventilacion", "label": "Ventilación"},
    {"id": "extraccion", "label": "Extracción"},
    {"id": "presurizacion", "label": "Presurización"},
    {"id": "mantencion", "label": "Mantención"},
    {"id": "otros", "label": "Otros"},
]


PROJECTS = [
    {
        "slug": "hospital-luis-calvo-mackenna-climatizacion",
        "name": "Sistema de climatización – Hospital Luis Calvo Mackenna",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Referencia de trabajo en salud, con soluciones HVAC para un recinto clínico que requiere continuidad operativa y control técnico del aire.",
        "description": "Proyecto representativo del CV de la empresa, vinculado a climatización y soporte técnico para infraestructura de salud, con foco en ejecución ordenada y respuesta en terreno.",
        "sector": "Salud y recintos clínicos",
        "reference": "Salud",
        "services": ["Climatización", "Ventilación"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": True,
    },
    {
        "slug": "hiper-lider-departamental-remodelacion",
        "name": "Remodelación HVAC – Hiper Líder Departamental",
        "category": "ventilacion",
        "location": "Santiago",
        "summary": "Proyecto de retail de alto flujo con trabajo técnico orientado a remodelación, ventilación y acondicionamiento de aire en recinto comercial.",
        "description": "Referencia construida a partir del CV de MAX SERVICES SPA para representar experiencia en supermercados y remodelaciones donde la coordinación de faena y la continuidad del servicio importan.",
        "sector": "Retail y supermercados",
        "reference": "Retail",
        "services": ["Ventilación", "Climatización"],
        "asset_dir": "assets/projects/ventilacion-retail-nunoa",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": True,
    },
    {
        "slug": "oficinas-inverko-climatizacion",
        "name": "Climatización para oficinas corporativas – Inverko",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Trabajo corporativo orientado a climatización y confort interior en oficinas, con criterio técnico y buena terminación visible.",
        "description": "Proyecto representativo de la experiencia de MAX SERVICES SPA en oficinas y espacios de trabajo, considerando montaje, ajuste y coordinación con la operación normal del cliente.",
        "sector": "Oficinas y corporativo",
        "reference": "Oficinas",
        "services": ["Climatización", "Mantención"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": True,
    },
    {
        "slug": "universidad-diego-portales-climatizacion",
        "name": "Climatización institucional – Universidad Diego Portales",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Referencia de trabajo para infraestructura universitaria, con soluciones de aire y climatización en recintos institucionales de uso continuo.",
        "description": "Proyecto representativo de la experiencia de la empresa en universidades e instituciones, donde la continuidad, el confort y la planificación técnica forman parte del resultado esperado.",
        "sector": "Universidades e instituciones",
        "reference": "Institucional",
        "services": ["Climatización", "Ventilación"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": False,
    },
    {
        "slug": "lider-general-velasquez-alameda-remodelacion",
        "name": "Remodelación técnica – Líder General Velásquez / Alameda",
        "category": "extraccion",
        "location": "Santiago",
        "summary": "Trabajo representativo de remodelación en retail, con soluciones de aire y adecuaciones técnicas para espacios comerciales de alto uso.",
        "description": "Referencia basada en el CV de MAX SERVICES SPA para reflejar participación en proyectos comerciales donde el orden de ejecución y la compatibilidad con la operación son determinantes.",
        "sector": "Retail y supermercados",
        "reference": "Retail",
        "services": ["Extracción", "Ventilación"],
        "asset_dir": "assets/projects/ventilacion-retail-nunoa",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": False,
    },
    {
        "slug": "universidad-autonoma-de-chile",
        "name": "Soluciones de aire – Universidad Autónoma de Chile",
        "category": "climatizacion",
        "location": "Temuco y Talca",
        "summary": "Participación en proyectos vinculados a climatización y soporte técnico para infraestructura universitaria en regiones.",
        "description": "Referencia institucional del CV de la empresa para mostrar experiencia fuera de Santiago, con criterios de montaje, coordinación y continuidad operacional.",
        "sector": "Universidades e instituciones",
        "reference": "Regiones",
        "services": ["Climatización", "Mantención"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": False,
    },
    {
        "slug": "presurizacion-edificios-residenciales",
        "name": "Presurización y ventilación – Edificios residenciales y comunidades",
        "category": "presurizacion",
        "location": "Santiago y regiones",
        "summary": "Experiencia en proyectos para edificios residenciales, comunidades y obras inmobiliarias donde seguridad, flujo de aire y continuidad son clave.",
        "description": "Referencia construida sobre la trayectoria de MAX SERVICES SPA en presurización de caja de escaleras, ventilación y soporte HVAC para edificios residenciales y comunidades.",
        "sector": "Edificios y comunidades",
        "reference": "Residencial",
        "services": ["Presurización", "Ventilación", "Mantención"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": False,
    },
    {
        "slug": "constructores-e-inmobiliarias-hvac",
        "name": "Montaje y soporte HVAC – Constructoras e inmobiliarias",
        "category": "otros",
        "location": "Santiago",
        "summary": "Experiencia técnica acumulada en obras y montajes para empresas como Boetsch, Echeverría Izquierdo, Carrán, Desco, Ormuz y otras constructoras.",
        "description": "Ficha representativa para resumir parte del trabajo desarrollado con constructoras e inmobiliarias, donde se requiere suministro, montaje, coordinación de obra y respuesta técnica confiable.",
        "sector": "Constructoras e inmobiliarias",
        "reference": "Obra",
        "services": ["Proyectos", "Extracción", "Presurización"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.png",
        "gallery": ["gallery-01.png"],
        "featured": False,
    },
]


def get_project_catalog():
    return {
        "categories": PROJECT_CATEGORIES,
        "projects": PROJECTS,
    }
