PROJECT_CATEGORIES = [
    {"id": "all", "label": "Todos"},
    {"id": "terminado", "label": "Terminados"},
    {"id": "en-ejecucion", "label": "En ejecución"},
    {"id": "climatizacion", "label": "Climatización"},
    {"id": "ventilacion", "label": "Ventilación"},
    {"id": "extraccion", "label": "Extracción"},
    {"id": "presurizacion", "label": "Presurización"},
    {"id": "mantencion", "label": "Mantención"},
    {"id": "otros", "label": "Otros"},
]


PROJECTS = [
    # ── Proyectos terminados ──────────────────────────────────────────────────
    {
        "slug": "edificio-residencial-vista-parque",
        "name": "Edificio Residencial Vista Parque",
        "category": "terminado",
        "location": "Av. Las Pipcas 4219, Santiago",
        "summary": "Instalación de sistemas HVAC en edificio residencial de alta terminación. Climatización, ventilación y presurización de caja de escalera.",
        "description": "Proyecto terminado en edificio residencial Vista Parque, con soluciones completas de climatización y ventilación para todos los pisos. Coordinación con constructora e inmobiliaria durante toda la ejecución.",
        "sector": "Edificios residenciales",
        "reference": "Terminado",
        "services": ["Climatización", "Ventilación", "Presurización"],
        "asset_dir": "assets/projects/edificio-vista-parque",
        "cover": "cover.webp",
        "gallery": ["cover.webp"],
        "featured": True,
    },
    {
        "slug": "edificio-residencial-tasco-boetsch",
        "name": "Edificio Residencial – TASCO Boetsch",
        "category": "terminado",
        "location": "Santiago",
        "summary": "Sistema de presurización y ventilación en edificio residencial ejecutado para TASCO Boetsch. Obra entregada con plena conformidad.",
        "description": "Proyecto finalizado en coordinación con TASCO Boetsch Edificaciones. Suministro, montaje y puesta en marcha de equipos de climatización y presurización para edificio residencial de varios pisos.",
        "sector": "Edificios residenciales",
        "reference": "Terminado",
        "services": ["Presurización", "Ventilación"],
        "asset_dir": "assets/projects/edificio-tasco-terminado",
        "cover": "cover.webp",
        "gallery": ["cover.webp"],
        "featured": True,
    },
    {
        "slug": "edificio-mixto-independencia-1760",
        "name": "Edificio Mixto – Av. Independencia 1760",
        "category": "terminado",
        "location": "Av. Independencia 1760, Santiago",
        "summary": "Climatización y ventilación en edificio de uso mixto (residencial + comercial). Local comercial en primer piso, departamentos en altura.",
        "description": "Obra terminada en edificio de uso mixto con planta comercial en primer piso. Instalación de sistemas de ventilación, extracción y climatización para residentes y locales. Coordinación directa con la administración del edificio.",
        "sector": "Edificios mixtos",
        "reference": "Terminado",
        "services": ["Climatización", "Ventilación", "Extracción"],
        "asset_dir": "assets/projects/edificio-1760",
        "cover": "cover.webp",
        "gallery": ["cover.webp", "gallery-01.webp"],
        "featured": True,
    },
    {
        "slug": "edificio-residencial-1840",
        "name": "Edificio Residencial – 1840",
        "category": "terminado",
        "location": "Santiago",
        "summary": "Suministro y montaje de sistemas HVAC en edificio residencial moderno. Entregado con altos estándares de confort y calidad de aire.",
        "description": "Proyecto residencial de mediana altura con instalación completa de climatización y ventilación. MAX SERVICES SPA participó desde el diseño hasta la puesta en marcha.",
        "sector": "Edificios residenciales",
        "reference": "Terminado",
        "services": ["Climatización", "Ventilación"],
        "asset_dir": "assets/projects/edificio-1840",
        "cover": "cover.webp",
        "gallery": ["cover.webp", "gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "edificio-patrimonial-ladrillo",
        "name": "Edificio Patrimonial – Renovación HVAC",
        "category": "terminado",
        "location": "Santiago",
        "summary": "Actualización de sistemas de ventilación y extracción en edificio de valor patrimonial. Trabajo técnico con respeto por la arquitectura existente.",
        "description": "Proyecto de renovación en edificio de ladrillo con instalaciones existentes. Remoción y reemplazo de equipos obsoletos, montaje de nuevos sistemas de ventilación y extracción con mínima intervención estructural.",
        "sector": "Edificios y patrimonio",
        "reference": "Terminado",
        "services": ["Ventilación", "Extracción", "Mantención"],
        "asset_dir": "assets/projects/edificio-ladrillo",
        "cover": "cover.webp",
        "gallery": ["cover.webp", "gallery-01.webp"],
        "featured": False,
    },
    # ── Proyectos en ejecución ────────────────────────────────────────────────
    {
        "slug": "obra-inmobiliaria-la-fontana-11-pisos",
        "name": "Obra en ejecución – Inmobiliaria La Fontana",
        "category": "en-ejecucion",
        "location": "Santiago",
        "summary": "Proyecto habitacional/comercial de 11 pisos actualmente en ejecución. MAX SERVICES SPA a cargo de sistemas de climatización y presurización.",
        "description": "Edificio de uso mixto de 11 pisos (Permiso de Edificación N°17235, Inmobiliaria La Fontana S.A.). Participación en montaje y coordinación de sistemas HVAC desde etapas tempranas de la obra.",
        "sector": "Construcción y obras nuevas",
        "reference": "En ejecución",
        "services": ["Climatización", "Presurización", "Ventilación"],
        "asset_dir": "assets/projects/obra-la-fontana",
        "cover": "cover.webp",
        "gallery": ["cover.webp"],
        "featured": False,
    },
    {
        "slug": "obra-echeverria-izquierdo-edificaciones",
        "name": "Obra en ejecución – Echeverría Izquierdo",
        "category": "en-ejecucion",
        "location": "Santiago",
        "summary": "Montaje de sistemas HVAC en obra de Echeverría Izquierdo Edificaciones. Coordinación técnica en terreno durante la etapa de estructura.",
        "description": "Proyecto en ejecución para Echeverría Izquierdo Edificaciones, una de las principales constructoras del país. MAX SERVICES SPA participa en la instalación de ductos, equipos de ventilación y presurización desde la etapa de obra gruesa.",
        "sector": "Constructoras e inmobiliarias",
        "reference": "En ejecución",
        "services": ["Ventilación", "Extracción", "Presurización"],
        "asset_dir": "assets/projects/obra-echeverria-izquierdo",
        "cover": "cover.webp",
        "gallery": ["cover.webp", "gallery-01.webp", "gallery-02.webp"],
        "featured": False,
    },
    {
        "slug": "obra-tasco-boetsch-en-ejecucion",
        "name": "Obra en ejecución – TASCO Boetsch",
        "category": "en-ejecucion",
        "location": "Santiago",
        "summary": "Nuevo proyecto en curso con TASCO Boetsch. Instalación de sistemas de presurización y ventilación en etapa de estructura.",
        "description": "Segunda participación de MAX SERVICES SPA con TASCO Boetsch Edificaciones. Montaje progresivo de equipos HVAC coordinado con el avance de la obra, garantizando calidad de instalación y cumplimiento de plazos.",
        "sector": "Constructoras e inmobiliarias",
        "reference": "En ejecución",
        "services": ["Presurización", "Ventilación"],
        "asset_dir": "assets/projects/obra-tasco-boetsch",
        "cover": "cover.webp",
        "gallery": ["cover.webp"],
        "featured": False,
    },
    # ── Proyectos de referencia (CV) ──────────────────────────────────────────
    {
        "slug": "hospital-luis-calvo-mackenna-climatizacion",
        "name": "Sistema de climatización – Hospital Luis Calvo Mackenna",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Referencia de trabajo en salud, con soluciones HVAC para un recinto clínico que requiere continuidad operativa y control técnico del aire.",
        "description": "Proyecto representativo del CV de la empresa, vinculado a climatización y soporte técnico para infraestructura de salud, con foco en ejecución ordenada y respuesta en terreno.",
        "sector": "Salud y recintos clínicos",
        "reference": "Salud",
        "services": ["Climatización", "Ventilación"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "hiper-lider-departamental-remodelacion",
        "name": "Remodelación HVAC – Hiper Líder Departamental",
        "category": "ventilacion",
        "location": "Santiago",
        "summary": "Proyecto de retail de alto flujo con trabajo técnico orientado a remodelación, ventilación y acondicionamiento de aire en recinto comercial.",
        "description": "Referencia construida a partir del CV de MAX SERVICES SPA para representar experiencia en supermercados y remodelaciones donde la coordinación de faena y la continuidad del servicio importan.",
        "sector": "Retail y supermercados",
        "reference": "Retail",
        "services": ["Ventilación", "Climatización"],
        "asset_dir": "assets/projects/ventilacion-retail-nunoa",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "oficinas-inverko-climatizacion",
        "name": "Climatización para oficinas corporativas – Inverko",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Trabajo corporativo orientado a climatización y confort interior en oficinas, con criterio técnico y buena terminación visible.",
        "description": "Proyecto representativo de la experiencia de MAX SERVICES SPA en oficinas y espacios de trabajo, considerando montaje, ajuste y coordinación con la operación normal del cliente.",
        "sector": "Oficinas y corporativo",
        "reference": "Oficinas",
        "services": ["Climatización", "Mantención"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "universidad-diego-portales-climatizacion",
        "name": "Climatización institucional – Universidad Diego Portales",
        "category": "climatizacion",
        "location": "Santiago",
        "summary": "Referencia de trabajo para infraestructura universitaria, con soluciones de aire y climatización en recintos institucionales de uso continuo.",
        "description": "Proyecto representativo de la experiencia de la empresa en universidades e instituciones, donde la continuidad, el confort y la planificación técnica forman parte del resultado esperado.",
        "sector": "Universidades e instituciones",
        "reference": "Institucional",
        "services": ["Climatización", "Ventilación"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "lider-general-velasquez-alameda-remodelacion",
        "name": "Remodelación técnica – Líder General Velásquez / Alameda",
        "category": "extraccion",
        "location": "Santiago",
        "summary": "Trabajo representativo de remodelación en retail, con soluciones de aire y adecuaciones técnicas para espacios comerciales de alto uso.",
        "description": "Referencia basada en el CV de MAX SERVICES SPA para reflejar participación en proyectos comerciales donde el orden de ejecución y la compatibilidad con la operación son determinantes.",
        "sector": "Retail y supermercados",
        "reference": "Retail",
        "services": ["Extracción", "Ventilación"],
        "asset_dir": "assets/projects/ventilacion-retail-nunoa",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "universidad-autonoma-de-chile",
        "name": "Soluciones de aire – Universidad Autónoma de Chile",
        "category": "climatizacion",
        "location": "Temuco y Talca",
        "summary": "Participación en proyectos vinculados a climatización y soporte técnico para infraestructura universitaria en regiones.",
        "description": "Referencia institucional del CV de la empresa para mostrar experiencia fuera de Santiago, con criterios de montaje, coordinación y continuidad operacional.",
        "sector": "Universidades e instituciones",
        "reference": "Regiones",
        "services": ["Climatización", "Mantención"],
        "asset_dir": "assets/projects/climatizacion-oficinas-las-condes",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "presurizacion-edificios-residenciales",
        "name": "Presurización y ventilación – Edificios residenciales y comunidades",
        "category": "presurizacion",
        "location": "Santiago y regiones",
        "summary": "Experiencia en proyectos para edificios residenciales, comunidades y obras inmobiliarias donde seguridad, flujo de aire y continuidad son clave.",
        "description": "Referencia construida sobre la trayectoria de MAX SERVICES SPA en presurización de caja de escaleras, ventilación y soporte HVAC para edificios residenciales y comunidades.",
        "sector": "Edificios y comunidades",
        "reference": "Residencial",
        "services": ["Presurización", "Ventilación", "Mantención"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
    {
        "slug": "constructores-e-inmobiliarias-hvac",
        "name": "Montaje y soporte HVAC – Constructoras e inmobiliarias",
        "category": "otros",
        "location": "Santiago",
        "summary": "Experiencia técnica acumulada en obras y montajes para empresas como Boetsch, Echeverría Izquierdo, Carrán, Desco, Ormuz y otras constructoras.",
        "description": "Ficha representativa para resumir parte del trabajo desarrollado con constructoras e inmobiliarias, donde se requiere suministro, montaje, coordinación de obra y respuesta técnica confiable.",
        "sector": "Constructoras e inmobiliarias",
        "reference": "Obra",
        "services": ["Proyectos", "Extracción", "Presurización"],
        "asset_dir": "assets/projects/presurizacion-edificio-providencia",
        "cover": "cover.webp",
        "gallery": ["gallery-01.webp"],
        "featured": False,
    },
]


def get_project_catalog():
    return {
        "categories": PROJECT_CATEGORIES,
        "projects": PROJECTS,
    }
